name: Wisecow CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2️⃣ Set up Docker Buildx for multi-platform builds
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # 3️⃣ Log in to Docker registry
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 4️⃣ Build and push Docker image
    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/wisecow:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/wisecow:latest

    # 5️⃣ Set up Kubernetes CLI
    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'v1.28.0'

    # 6️⃣ Deploy to Kubernetes
    - name: Deploy Wisecow to Kubernetes
      env:
        KUBECONFIG_DATA: ${{ secrets.KUBECONFIG }}
      run: |
        # Write kubeconfig to file
        echo "$KUBECONFIG_DATA" | base64 --decode > kubeconfig
        export KUBECONFIG=$(pwd)/kubeconfig

        # Update image in deployment
        kubectl set image deployment/wisecow-deployment wisecow=${{ secrets.DOCKER_USERNAME }}/wisecow:latest -n default

        # Apply service & ingress (with TLS)
        kubectl apply -f k8s/service.yaml
        kubectl apply -f k8s/ingress.yaml

        # Rollout status check
        kubectl rollout status deployment/wisecow-deployment -n default

